[package]
name = "macro_find_and_replace"
version = "0.9.0"
authors = ["Noam Elul <noamelul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true
name = "macro_find_and_replace"

[dependencies]
